os:
- linux

language: crystal

script:
- crystal build hello.cr -o hello-$TRAVIS_OS_NAME

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  skip_cleanup: true

  file:
  - hello-linux

  on:
    repo: DannyBen/travistest
