os: [linux, osx]
language: crystal
notifications: { email: false }

script:
# ==> Testing steps
# - crystal spec
# - crystal tool format --check

# ==> Build binary based on Travis OS (osx / linux)
- crystal build hello.cr --release -o hello-$TRAVIS_OS_NAME

# ==> Additionally, build an alpine binary using external docker
- >-
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    docker run --rm -it -v $PWD:/app dannyben/crystal build --static --release -o hello-alpine hello.cr
  fi

# ==> Push everything to the GitHub tag release
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  skip_cleanup: true
  overwrite: true
  # draft: true

  file:
  - hello-linux
  - hello-alpine
  - hello-osx

  on:
    repo: DannyBen/travistest
    tags: true
