os:
- linux
- osx

language: crystal

notifications:
  email: false

script:
- crystal build hello.cr --release -o hello-$TRAVIS_OS_NAME

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  skip_cleanup: true
  draft: true

  file:
  - hello-linux
  - hello-osx

  on:
    repo: DannyBen/travistest
