language: ruby

notifications:
  email: false

rvm:
- "2.5.0"

before_install:
- sudo apt-get update
- sudo apt-get install python3.6 -y

install:
- pip install codenamize

script: 
- ruby -v
- python -v
- codenamize -v
