os:
- linux
- osx

language: crystal

notifications:
  email: false

script:
# - crystal spec
# - crystal tool format --check
- crystal build hello.cr --release -o hello-$TRAVIS_OS_NAME
# - |
#   if [ "$TRAVIS_OS_NAME" = "linux" ]
#     echo docker run --rm -it -v $PWD:/app dannyben/crystal build --release -o hello-alpine
#   fi

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  skip_cleanup: true
  draft: true

  file:
  - hello-linux
  - hello-osx

  on:
    repo: DannyBen/travistest
    tags: true