language: ruby

notifications:
  email: false

rvm:
- "2.5.0"

# before_install: 
# - source ~/virtualenv/python3.6/bin/activate

install:
- pip3 install --user codenamize

script: 
- codenamize --version
