source "https://rubygems.org"

gem 'jekyll'

gem 'byebug'
gem 'rack-test'
gem 'rdoc'
gem 'rspec'
gem 'rspec-html-matchers'
gem 'rspec_fixtures'
gem 'runfile'
gem 'runfile-tasks'
gem 'simplecov'
gem 'yard'

gem 'coderay', '~> 1.1'
gem 'colsole', '~> 0.5'
gem 'commonmarker', '~> 0.20'
gem 'docopt', '~> 0.6'
gem 'ferret', '~> 0.11'
gem 'json', '~> 2.1'
gem 'naturally', '~> 2.2'
gem 'os', '~> 1.0'
gem 'puma', '~> 4.0'
gem 'rack-contrib', '~> 2.1'
gem 'rack-ssl', '~> 1.4'
gem 'requires', '~> 0.1'
gem 'sass', '~> 3.7'
gem 'sinatra', '~> 2.0', '>= 2.0.5'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.5'
gem 'slim', '~> 4.0'
